import type { ITheme } from "@xterm/xterm";
import type { ThemePresetId } from "../../state/terminal.svelte";

export type ThemePresetMeta = { id: ThemePresetId; label: string; subtitle: string };

export const THEME_PRESETS: ThemePresetMeta[] = [
  { id: "rift",           label: "Rift default",   subtitle: "Tracks app theme tokens" },
  { id: "dracula",        label: "Dracula",        subtitle: "Classic purple/pink" },
  { id: "solarized-dark", label: "Solarized Dark", subtitle: "Ethan Schoonover" },
  { id: "monokai",        label: "Monokai",        subtitle: "TextMate classic" },
  { id: "github-dark",    label: "GitHub Dark",    subtitle: "Editor-matched" },
];

type ReadVarFn = (name: string, fallback: string) => string;

export function buildPresetTheme(id: ThemePresetId, readVar: ReadVarFn): ITheme {
  if (id === "rift") {
    return {
      background: readVar("--bg", "#0f1117"),
      foreground: readVar("--fg", "#f4f4f5"),
      cursor: readVar("--accent", "#a78bfa"),
      cursorAccent: readVar("--bg", "#0f1117"),
      selectionBackground: readVar("--accent-soft", "#a78bfa33"),
      black: "#1f2128",
      red: readVar("--danger", "#f87171"),
      green: "#86efac",
      yellow: readVar("--warn", "#fbbf24"),
      blue: readVar("--info", "#38bdf8"),
      magenta: readVar("--accent", "#a78bfa"),
      cyan: readVar("--info", "#38bdf8"),
      white: readVar("--fg", "#f4f4f5"),
      brightBlack: "#3f3f46",
      brightRed: readVar("--danger", "#f87171"),
      brightGreen: "#86efac",
      brightYellow: readVar("--warn", "#fbbf24"),
      brightBlue: readVar("--info", "#38bdf8"),
      brightMagenta: readVar("--accent", "#a78bfa"),
      brightCyan: readVar("--info", "#38bdf8"),
      brightWhite: "#ffffff",
    };
  }
  return STATIC_PRESETS[id];
}

const STATIC_PRESETS: Record<Exclude<ThemePresetId, "rift">, ITheme> = {
  dracula: {
    background: "#282a36",
    foreground: "#f8f8f2",
    cursor: "#f8f8f0",
    cursorAccent: "#282a36",
    selectionBackground: "#44475a",
    black: "#21222c",
    red: "#ff5555",
    green: "#50fa7b",
    yellow: "#f1fa8c",
    blue: "#bd93f9",
    magenta: "#ff79c6",
    cyan: "#8be9fd",
    white: "#f8f8f2",
    brightBlack: "#6272a4",
    brightRed: "#ff6e6e",
    brightGreen: "#69ff94",
    brightYellow: "#ffffa5",
    brightBlue: "#d6acff",
    brightMagenta: "#ff92df",
    brightCyan: "#a4ffff",
    brightWhite: "#ffffff",
  },
  "solarized-dark": {
    background: "#002b36",
    foreground: "#839496",
    cursor: "#93a1a1",
    cursorAccent: "#002b36",
    selectionBackground: "#073642",
    black: "#073642",
    red: "#dc322f",
    green: "#859900",
    yellow: "#b58900",
    blue: "#268bd2",
    magenta: "#d33682",
    cyan: "#2aa198",
    white: "#eee8d5",
    brightBlack: "#586e75",
    brightRed: "#cb4b16",
    brightGreen: "#586e75",
    brightYellow: "#657b83",
    brightBlue: "#839496",
    brightMagenta: "#6c71c4",
    brightCyan: "#93a1a1",
    brightWhite: "#fdf6e3",
  },
  monokai: {
    background: "#272822",
    foreground: "#f8f8f2",
    cursor: "#f8f8f0",
    cursorAccent: "#272822",
    selectionBackground: "#49483e",
    black: "#272822",
    red: "#f92672",
    green: "#a6e22e",
    yellow: "#f4bf75",
    blue: "#66d9ef",
    magenta: "#ae81ff",
    cyan: "#a1efe4",
    white: "#f8f8f2",
    brightBlack: "#75715e",
    brightRed: "#f92672",
    brightGreen: "#a6e22e",
    brightYellow: "#f4bf75",
    brightBlue: "#66d9ef",
    brightMagenta: "#ae81ff",
    brightCyan: "#a1efe4",
    brightWhite: "#f9f8f5",
  },
  "github-dark": {
    background: "#0d1117",
    foreground: "#c9d1d9",
    cursor: "#58a6ff",
    cursorAccent: "#0d1117",
    selectionBackground: "#1f6feb55",
    black: "#484f58",
    red: "#ff7b72",
    green: "#3fb950",
    yellow: "#d29922",
    blue: "#58a6ff",
    magenta: "#bc8cff",
    cyan: "#39c5cf",
    white: "#b1bac4",
    brightBlack: "#6e7681",
    brightRed: "#ffa198",
    brightGreen: "#56d364",
    brightYellow: "#e3b341",
    brightBlue: "#79c0ff",
    brightMagenta: "#d2a8ff",
    brightCyan: "#56d4dd",
    brightWhite: "#f0f6fc",
  },
};
