#!/usr/bin/env python3
"""Emit docs/audit-2026-06-04/PHASE2-backend.md — every worklist finding NOT yet
in .tmp/edit-done.json, grouped by category + priority, so the next session can
clear the whole remaining list (Rust + security + held frontend) in one pass.

Re-runnable: append IDs to edit-done.json as you go, re-run to see what's left.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKLIST = os.path.join(ROOT, "docs/audit-2026-06-04/edit-worklist.json")
DONE = os.path.join(ROOT, ".tmp/edit-done.json")
OUT = os.path.join(ROOT, "docs/audit-2026-06-04/PHASE2-backend.md")

SEC = (
    "inject",
    "traversal",
    "scheme",
    "sanitiz",
    " xss",
    "dompurify",
    "allowlist",
    "url ",
    "releaseurl",
    "validate_path",
    "file://",
    "javascript:",
    "bypass",
    "capabilit",
    "permission-mode",
    "plaintext",
    "keychain",
    "wildcard",
    "data: uri",
    "data: uri",
    "unsanitiz",
    "unvalidated",
)
DEP = ("vitest", "ghsa", "cve-", "esbuild", "vite-node", "advisory")
DEAD = ("dead ", "unreferenced", "orphan", "stripped")


def norm(f):
    return f.replace("\\", "/")


def is_rust(x):
    return "src-tauri" in norm(x["file"])


def txt(x):
    return (
        x["title"] + " " + x.get("description", "") + " " + x.get("suggested_fix", "")
    ).lower()


def is_sec(x):
    return any(k in txt(x) for k in SEC)


def is_dep(x):
    return any(k in txt(x) for k in DEP)


def is_dead(x):
    s = (x["title"] + " " + x.get("suggested_fix", "")).lower()
    return any(k in s for k in DEAD) and ("delete" in s or "remove" in s or "dead" in s)


def cat(x):
    # security spans both rust + frontend; check first
    if is_dep(x):
        return "deps"
    if is_sec(x):
        return "security (rust)" if is_rust(x) else "security (frontend)"
    if is_dead(x):
        return "dead-code (flag-not-delete)"
    if is_rust(x):
        return "rust"
    return "frontend (held / missed)"


ORDER = [
    "security (rust)",
    "security (frontend)",
    "frontend (held / missed)",
    "rust",
    "deps",
    "dead-code (flag-not-delete)",
]


def main():
    d = json.load(open(WORKLIST, encoding="utf-8"))["findings"]
    done = set(json.load(open(DONE, encoding="utf-8")))
    rem = [x for x in d if x["id"] not in done]
    groups = {}
    for x in rem:
        groups.setdefault(cat(x), []).append(x)

    lines = []
    lines.append("# Phase 2 — Backend + remaining audit findings")
    lines.append("")
    lines.append(
        f"> Auto-generated by `scripts/phase2-list.py`. {len(rem)} findings remain "
        f"(worklist {len(d)} − done {len(done)}). Re-run after appending IDs to "
        "`.tmp/edit-done.json` to refresh."
    )
    lines.append("")
    lines.append(
        "**Procedure:** quit dev (`rift-tauri.exe` EXACTLY — never a `rift*` glob; "
        "`rift.exe` is prod) → `cargo check --manifest-path src-tauri/Cargo.toml` "
        "baseline → fix in file-clusters → re-`cargo check` + `npm run check` → scoped "
        "commit → append IDs. Many are stale (audit ran on an old baseline) — verify "
        "before editing; record verified-already-fixed as done too."
    )
    lines.append("")
    for g in ORDER:
        items = groups.get(g, [])
        if not items:
            continue
        lines.append(f"## {g} ({len(items)})")
        lines.append("")
        for x in sorted(items, key=lambda y: (norm(y["file"]), y["line"])):
            f = norm(x["file"]).split("rift-tauri/")[-1]
            lines.append(
                f"- **{x['id']}** [{x['severity']}] `{f}:{x['line']}` — {x['title']}"
            )
        lines.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    print(f"wrote {OUT} | {len(rem)} remaining")
    for g in ORDER:
        if groups.get(g):
            print(f"  {g}: {len(groups[g])}")


if __name__ == "__main__":
    main()
