#!/usr/bin/env python3
"""Assemble the rift-audit-swarm workflow result into a markdown report.

Usage: python scripts/audit-assemble.py <task-output-file> [out.md] [date]
  <task-output-file>  the wf task .output file (JSON: {summary,agentCount,logs,result})
  out.md              destination (default: docs/AUDIT-<date>.md)
  date                report date (default: 2026-06-04)
"""

import json
import sys
import os


def load_result(path):
    d = json.load(open(path, encoding="utf-8"))
    r = d.get("result", d)
    if isinstance(r, str):
        r = json.loads(r)
    return r, d.get("agentCount"), d.get("logs", [])


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    src = sys.argv[1]
    date = sys.argv[3] if len(sys.argv) > 3 else "2026-06-04"
    out = sys.argv[2] if len(sys.argv) > 2 else f"docs/AUDIT-{date}.md"
    r, agent_count, logs = load_result(src)

    sev = r.get("severityCounts", {}) or {}
    order = ["critical", "high", "medium", "low"]
    sev_line = " · ".join(f"**{sev.get(k, 0)}** {k}" for k in order)
    sections = sorted(
        r.get("sections", []) or [], key=lambda s: -(s.get("confirmed_count", 0) or 0)
    )

    L = []
    L.append(f"# Rift — Full Codebase Audit ({date})")
    L.append("")
    L.append(
        f"> Generated by the `rift-audit-swarm` workflow. "
        f"{r.get('finderCount', '?')} finder agents → adversarial verification → synthesis."
    )
    L.append(
        f"> **{r.get('confirmedCount', '?')} confirmed findings** "
        f"(after refute-by-default verification): {sev_line}."
    )
    if agent_count:
        L.append(f"> Total agents: {agent_count}.")
    L.append("")
    L.append("## Confirmed findings by area")
    L.append("")
    L.append("| Area | Confirmed |")
    L.append("|---|---|")
    for s in sections:
        L.append(f"| {s.get('bucket', '?')} | {s.get('confirmed_count', 0)} |")
    L.append("")
    L.append("---")
    L.append("")
    for s in sections:
        md = (s.get("markdown") or "").strip()
        if md:
            L.append(md)
            L.append("")
            L.append("---")
            L.append("")
    crit = (r.get("criticNote") or "").strip()
    if crit:
        L.append("## Coverage gaps & recommended follow-up")
        L.append("")
        L.append(
            "> From the completeness critic — what this pass likely under-covered."
        )
        L.append("")
        L.append(crit)
        L.append("")

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    open(out, "w", encoding="utf-8").write("\n".join(L))
    print(
        f"wrote {out}  ({len(L)} lines, {len(sections)} sections, "
        f"{r.get('confirmedCount')} confirmed)"
    )


if __name__ == "__main__":
    main()
