#!/usr/bin/env python3
"""Split the rift-audit-swarm result into an organized markdown folder.

Usage: python scripts/audit-split.py <task-output-file> <out-dir> [date]
"""

import json
import sys
import os
import re


def slug(s):
    s = s.lower().replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


# logical ordering by domain; lower number = earlier file
def rank(bucket):
    b = bucket.lower()
    if b.startswith("backend"):
        return (1, bucket)
    if b.startswith("frontend"):
        return (2, bucket)
    return (3, bucket)  # cross-cutting


SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def load(path):
    d = json.load(open(path, encoding="utf-8"))
    r = d.get("result", d)
    if isinstance(r, str):
        r = json.loads(r)
    return r, d.get("agentCount")


def sev_counts(items):
    c = {}
    for f in items:
        c[f.get("severity", "?")] = c.get(f.get("severity", "?"), 0) + 1
    return c


def main():
    src, outdir = sys.argv[1], sys.argv[2]
    date = sys.argv[3] if len(sys.argv) > 3 else "2026-06-04"
    r, agent_count = load(src)
    os.makedirs(outdir, exist_ok=True)

    sections = sorted(r.get("sections", []), key=lambda s: rank(s["bucket"]))
    raw = r.get("rawConfirmed", [])
    sev = r.get("severityCounts", {}) or {}

    # ---- map each section to a numbered filename ----
    files = {}  # bucket -> filename
    counters = {1: 10, 2: 20, 3: 30}
    for s in sections:
        dom = rank(s["bucket"])[0]
        fn = f"{counters[dom]}-{slug(s['bucket'])}.md"
        counters[dom] += 1
        files[s["bucket"]] = fn

    # ---- per-area files ----
    for s in sections:
        body = [
            f"# {s['bucket']}",
            "",
            f"_{s.get('confirmed_count', 0)} confirmed findings._ "
            f"[← back to index](README.md)",
            "",
            (s.get("markdown") or "").strip(),
            "",
        ]
        open(os.path.join(outdir, files[s["bucket"]]), "w", encoding="utf-8").write(
            "\n".join(body)
        )

    # ---- 00 priority triage: all high + medium ----
    actionable = sorted(
        [f for f in raw if f.get("severity") in ("critical", "high", "medium")],
        key=lambda f: (SEV_ORDER.get(f.get("severity"), 9), f.get("file", "")),
    )
    P = [
        "# Priority Triage — Critical / High / Medium",
        "",
        f"_{len(actionable)} findings worth acting on first._ [← back to index](README.md)",
        "",
    ]
    cur = None
    for f in actionable:
        if f["severity"] != cur:
            cur = f["severity"]
            P += [
                "",
                f"## {cur.upper()}",
                "",
                "| Title | Location | Fix |",
                "|---|---|---|",
            ]
        loc = f"`{f.get('file', '?')}:{f.get('line', '?')}`"
        fix = (
            (f.get("suggested_fix", "") or "")
            .replace("\n", " ")
            .replace("|", "\\|")[:180]
        )
        title = (f.get("title", "") or "").replace("|", "\\|")
        P.append(f"| {title} | {loc} | {fix} |")
    P.append("")
    open(os.path.join(outdir, "00-priority-triage.md"), "w", encoding="utf-8").write(
        "\n".join(P)
    )

    # ---- coverage gaps ----
    crit = (r.get("criticNote") or "").strip()
    if crit:
        open(os.path.join(outdir, "90-coverage-gaps.md"), "w", encoding="utf-8").write(
            "# Coverage Gaps & Follow-up\n\n_From the completeness critic — what this pass likely "
            "under-covered._ [← back to index](README.md)\n\n" + crit + "\n"
        )

    # ---- README index ----
    order = ["critical", "high", "medium", "low"]
    sev_line = " · ".join(f"**{sev.get(k, 0)}** {k}" for k in order)
    R = [
        f"# Rift — Codebase Audit ({date})",
        "",
        f"Generated by the `rift-audit-swarm` workflow: **{r.get('finderCount', '?')} finder agents** "
        f"→ adversarial verification → synthesis"
        + (f" ({agent_count} agents total)." if agent_count else "."),
        "",
        f"## {r.get('confirmedCount', '?')} confirmed findings",
        "",
        f"{sev_line}",
        "",
        "> Every finding below survived a refute-by-default adversarial verifier that independently "
        "re-read the code. Severities were recalibrated by the verifier (over-rated findings downgraded).",
        "",
        "## Start here",
        "",
        "- **[00 — Priority Triage](00-priority-triage.md)** — all critical/high/medium in one actionable list",
        "- **[90 — Coverage Gaps](90-coverage-gaps.md)** — what the audit under-covered (next-pass work-list)",
        "",
        "## Findings by area",
        "",
        "| Area | Findings | Severity mix |",
        "|---|---|---|",
    ]
    by_bucket = {}
    for f in raw:
        by_bucket.setdefault(f.get("_bucket") or f.get("bucket"), []).append(f)
    for s in sections:
        items = by_bucket.get(s["bucket"], [])
        sc = sev_counts(items)
        mix = " ".join(f"{sc[k]}{k[0].upper()}" for k in order if sc.get(k))
        R.append(
            f"| [{s['bucket']}]({files[s['bucket']]}) | {len(items)} | {mix or '—'} |"
        )
    R += [
        "",
        "> Counts above are raw confirmed findings. Area files merge near-duplicate "
        "findings (same root cause, adjacent lines) into single rows, so a file's visible "
        "row count may be marginally lower.",
        "",
    ]
    R += ["", "## The 3 high-severity bugs", ""]
    for f in sorted(
        [x for x in raw if x.get("severity") == "high"], key=lambda x: x.get("file", "")
    ):
        R.append(f"- **{f.get('title')}** — `{f.get('file')}:{f.get('line')}`")
    R.append("")
    open(os.path.join(outdir, "README.md"), "w", encoding="utf-8").write("\n".join(R))

    print(
        f"wrote {outdir}/ : README + 00-priority + {len(sections)} area files + coverage-gaps"
    )
    print("files:", ", ".join(sorted(os.listdir(outdir))))


if __name__ == "__main__":
    main()
